app/urls.py
from django.urls import path
from app.views.home_view import Home

app_name = 'app'

urlpatterns = [
    path('', Home.as_view(), name='home'),
    path('tasks/<int:pk>/delete/', Home.as_view(), name='tasks'),
]

contas/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth import views as auth_view

from contas.forms import EmailLoginForm
from contas.views.criar_conta_view import CriarConta
from contas.views.editar_view import EditarPerfil

app_name = 'contas'

urlpatterns = [
    path('criarconta/', CriarConta.as_view(), name='criar_conta'),
    path('login/', auth_view.LoginView.as_view(template_name='login.html', authentication_form=EmailLoginForm), name='login'),
    path('logout/', auth_view.LogoutView.as_view(next_page=reverse_lazy('contas:login')), name='logout'),
    path('editarperfil/<int:pk>', EditarPerfil.as_view(), name='editar_perfil'),
    path('mudarsenha/<int:pk>', auth_view.PasswordChangeView.as_view(
        template_name='mudarsenha.html',
        success_url=reverse_lazy('app:home')),
        name='mudar_senha')
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls', namespace='app')),
    path('contas/', include('contas.urls', namespace='contas')),
]

contas/models/usuario.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from contas.models.usuario_manager import UsuarioManager


# Create your models here.
class Usuario(AbstractUser):
    username = None  # Anula o campo herdado
    email = models.EmailField(unique=True)
    first_name = models.CharField(max_length=30)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UsuarioManager()

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

contas/models/usuario_manager.py
from django.contrib.auth.base_user import BaseUserManager

class UsuarioManager(BaseUserManager):
    use_in_migrations = True

    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("O e-mail deve ser informado")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, **extra_fields):
        # garante que o superuser tenha permissões elevadas
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser precisa de is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser precisa de is_superuser=True.")
        return self.create_user(email, password, **extra_fields)

contas/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

from django import forms
from contas.models import Usuario


class UsuarioCreationForm(UserCreationForm):
    class Meta:
            model = Usuario
            fields = ('email',)

class EmailLoginForm(AuthenticationForm):
    username = forms.EmailField(
        label="Email",
        widget=forms.EmailInput(
            attrs={"autofocus": True, "autocomplete": "email"}
        )
    )

class CriarContaForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=True, label='Primeiro nome')
    email = forms.EmailField()

    class Meta(UserCreationForm):
        model = Usuario
        fields = ('first_name', 'last_name', 'email', 'password1', 'password2')

contas/views.py
from django.shortcuts import reverse
from django.views.generic import FormView

from contas.forms import CriarContaForm


class CriarConta(FormView):
    template_name = 'criar_conta.html'
    form_class = CriarContaForm

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('contas:login')

contas/views/criar_conta_view.py
from django.shortcuts import reverse
from django.views.generic import FormView

from contas.forms import CriarContaForm


class CriarConta(FormView):
    template_name = 'criar_conta.html'
    form_class = CriarContaForm

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def form_invalid(self, form):
        # 3) Quando o form NÃO for válido, re-renderiza o template
        #    incluindo form.errors no contexto
        return self.render_to_response(self.get_context_data(form=form))

    def get_success_url(self):
        return reverse('contas:login')

contas/views/editar_view.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import UpdateView
from django.shortcuts import reverse
from app.forms import SettingsForm
from contas.models import Usuario


# Create your views here.
class EditarPerfil(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    template_name = "editarperfil.html"
    form_class = SettingsForm
    model = Usuario

    def test_func(self):
        user = self.get_object()
        return self.request.user == user

    def get_success_url(self):
        return reverse('app:home')

contas/templates/criar_conta.html
{% extends 'base_contas.html' %}
{% load widget_tweaks %}

{% block title %}
    Cadastre-se
{% endblock title %}

{% block content_contas %}
    <div class="flex items-center justify-between w-full">
        <h1 class="text-3xl font-semibold">Cadastre-se!</h1>
        <a href="{% url 'contas:login' %}"
           class="fa-solid fa-arrow-left text-base cursor-pointer bg-gray-900 text-gray-200 p-2 rounded-full"></a>
    </div>
    <form method="post" class="w-full">
        {% csrf_token %}
        <fieldset class="flex flex-col gap-4 text-center">
            <legend class="text-14 leading-5 text-left mb-4">
                Cadastre-se e rapidamente otimize seu tempo e suas ideias.
            </legend>

            {# 2. Para cada campo, renderiza o input e logo abaixo mostra seus erros #}
            {% for campo in form %}
                <div class="flex flex-col">
                    {% render_field campo class="p-2 rounded-lg border-1 border-gray-400 bg-white" placeholder=campo.label %}
                    {% if campo.errors %}
                        {% for erro in campo.errors %}
                            <p class="text-red-600 text-sm mt-1">{{ erro }}</p>
                        {% endfor %}
                    {% endif %}
                </div>
            {% endfor %}
        </fieldset>
        <button type="submit"
                class="w-full bg-yellow-400 mt-4 p-2 rounded-lg font-semibold mb-2 cursor-pointer shadow-lg hover:shadow-indigo-500/50 trasition duration-400">
            Cadastrar
        </button>
        <div class="w-full flex justify-center text-lm gap-1">
            <label for="cadastrar-usuario">Já tem uma conta?</label>
            <a href="{% url 'contas:login' %}" id="cadastrar-usuario"
               class="text-blue-700 hover:text-blue-500 transition duration-300">
                Faça login
            </a>
        </div>
    </form>
{% endblock %}

contas/templates/editarperfil.html
{% extends 'base_home.html' %}
{% load widget_tweaks %}

{% block title %}
    Editar Perfil
{% endblock %}

{% block content_home %}
    <div class="flex items-center justify-between">
        <h1 class="text-3xl mb-1">Meu Perfil</h1>
        <a href="{% url 'app:home' %}"
           class="fa-solid fa-arrow-left text-base cursor-pointer bg-gray-900 text-gray-200 p-2 rounded-full"></a>
    </div>
    <form method="post" class="w-full">
        {% csrf_token %}
        <fieldset class="flex flex-col gap-3 text-center">
            <legend class="text-14 text-left leading-5 text-center mb-4">Gerencie suas informações pessoais
            </legend>
            {% for campo in form %}
                {% if campo.label != 'Senha' %}
                    <div class="flex flex-col">
                        <label class="text-left">{{ campo.label }}</label>
                        {% render_field campo class="p-2 rounded-lg border-1 border-gray-400 bg-white" %}
                    </div>
                {% endif %}
            {% endfor %}
        </fieldset>
        <fieldset class="flex w-full h-20 gap-2 mt-3">
            <div class="w-1/2 rounded-lg bg-indigo-200 opacity-90 flex flex-col items-center justify-center">
                <p class="text-xl font-semibold">{{ user.date_joined|date:"d/m/Y" }}</p>
                <p class="text-sm">Membro desde</p>
            </div>
            <div class="w-1/2 rounded-lg bg-indigo-200 opacity-90 flex flex-col items-center justify-center">
                {% if user.is_active %}
                    <i class="fa-solid fa-check text-xl"></i>
                    <p class="text-sm">Conta ativa</p>
                {% else %}
                    <i class="fa-solid fa-circle-xmark"></i>
                    <p class="text-sm">Conta inativa</p>
                {% endif %}
            </div>
        </fieldset>
        <button type="submit"
                class="w-full bg-yellow-400 mt-4 p-2 rounded-lg font-semibold mb-2 cursor-pointer shadow-lg hover:scale-101 hover:shadow-indigo-500/50 trasition duration-400">
            <i class="fas fa-save mr-2"></i>Salvar alterações
        </button>
    </form>
    <div class="w-full flex justify-center text-lm gap-1">
        <label for="cadastrar-usuario">Não lembra da senha?</label>
        <a href="{% url 'contas:mudar_senha' user.pk %}" id="cadastrar-usuario"
           class="text-blue-700 hover:text-blue-500 transition duration-300">
            Redefinir senha
        </a>
    </div>
{% endblock %}

contas/templates/login.html
{% extends 'base_contas.html' %}
{% load static %}
{% load widget_tweaks %}

{% block title %}
    Fazer login
{% endblock title %}

{% block content_contas %}
    <img src="{% static 'img/logo-python.png' %}" alt="Logo do Python" class="w-1/6">
    <h1 class="text-3xl mb-2 font-semibold">Seja bem vindo!</h1>
    <p class="text-14 leading-5 text-center">Organize suas atividades diárias de forma simples e sem
        preucupações.</p>
    <form action="{% url 'contas:login' %}" method="post" class="w-full">
        {% csrf_token %}
        <fieldset class="flex flex-col gap-4 text-center">
            <legend class="mb-2 font-semibold">Faça antes seu login para começar</legend>
            {% for campo in form %}
                {% render_field campo class="p-2 rounded-lg border-1 border-gray-400 bg-white" placeholder=campo.label %}
                {% for erro in campo.errors %}
                    <p class="text-red-600 text-sm mb-2">{{ erro }}</p>
                {% endfor %}
            {% endfor %}
        </fieldset>
        <button type="submit"
                class="w-full bg-yellow-400 mt-4 p-2 rounded-lg font-semibold shadow-lg hover:shadow-indigo-500/50 trasition duration-400">
            Entrar
        </button>
    </form>
    <div class="w-full">
        <div class="w-full flex justify-between text-lm">
            <label for="cadastrar-usuario">Ainda não tem uma conta?</label>
            <a href="{% url 'contas:criar_conta' %}" id="cadastrar-usuario"
               class="text-blue-700 hover:text-blue-500 transition duration-300">
                Cadastre-se
                <i class="fas fa-angle-right"></i>
            </a>
        </div>
        <div class="flex justify-center gap-3 mt-4">
            <a href="">
                <img src="{% static 'img/logo-google.png' %}" alt="Logo do Google" class="w-12">
            </a>
            <a href="">
                <img src="{% static 'img/logo-github.png' %}" alt="Logo do Github" class="w-12">
            </a>
        </div>
        <!-- <a href="">Esqueceu senha?</a> -->
    </div>
{% endblock %}

contas/templates/mudarsenha.html
{% extends 'base_home.html' %}
{% load widget_tweaks %}

{% block title %}
    Editar Perfil
{% endblock %}

{% block content_home %}
    <div class="flex items-center justify-between">
        <h1 class="text-3xl mb-1">Redefinir senha</h1>
        <a href="{% url 'contas:editar_perfil' user.pk %}"
           class="fa-solid fa-arrow-left text-base cursor-pointer bg-gray-900 text-gray-200 p-2 rounded-full"></a>
    </div>
    <form method="post" class="w-full">
        {% csrf_token %}
        <fieldset class="flex flex-col gap-3 text-center">
            <legend class="text-14 text-left leading-5 text-center mb-4">Atualize sua senha sem dificuldades
            </legend>
            {% for campo in form %}
                {% if campo.label != 'Senha' %}
                    <div class="flex flex-col">
                        <label class="text-left">{{ campo.label }}</label>
                        {% render_field campo class="p-2 rounded-lg border-1 border-gray-400 bg-white" %}
                    </div>
                {% endif %}
            {% endfor %}
        </fieldset>
        <button type="submit"
                class="w-full bg-yellow-400 mt-4 p-2 rounded-lg font-semibold mb-2 cursor-pointer shadow-lg hover:scale-101 hover:shadow-indigo-500/50 trasition duration-400">
            <i class="fas fa-save mr-2"></i>Salvar alterações
        </button>
    </form>
{% endblock %}